name: coverage
on: [push]

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Generate coverage report
        run: |
          cargo +nightly tarpaulin --verbose --out xml --tests --exclude-files benches/* --exclude-files ulua-sys/src/*/*

      - name: Upload report to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: false
